import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BarChart3, Bell, CheckCheck, LayoutDashboard, LogOut, Menu, Moon, PlusCircle, Sun, TicketCheck, Users, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { Link, NavLink, Outlet } from 'react-router-dom';
import { api } from '../api/client';
import { useAuth } from '../store/auth';
import type { ApiResponse } from '../types';

const links = [
  { to: '/', label: 'Overview', icon: LayoutDashboard }, { to: '/tickets', label: 'Tickets', icon: TicketCheck },
  { to: '/tickets/new', label: 'Raise ticket', icon: PlusCircle }, { to: '/users', label: 'User management', icon: Users, admin: true },
  { to: '/reports', label: 'Reports', icon: BarChart3, staff: true },
];
type Notification = { id: string; title: string; message: string; link?: string; readAt?: string; createdAt: string };

export function Layout() {
  const [open, setOpen] = useState(false); const [notificationsOpen, setNotificationsOpen] = useState(false);
  const [dark, setDark] = useState(() => localStorage.getItem('tms-theme') === 'dark');
  const { user, logout } = useAuth(); const panelRef = useRef<HTMLDivElement>(null);
  const staff = user?.role !== 'employee'; const admin = user?.role === 'super_admin' || user?.role === 'company_admin';
  useEffect(() => { document.documentElement.classList.toggle('dark', dark); localStorage.setItem('tms-theme', dark ? 'dark' : 'light'); }, [dark]);
  useEffect(() => { const close = (event: MouseEvent) => { if (panelRef.current && !panelRef.current.contains(event.target as Node)) setNotificationsOpen(false); }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close); }, []);
  return <div className="min-h-screen bg-slate-50 transition-colors dark:bg-slate-950"><aside className={`fixed inset-y-0 left-0 z-40 w-64 bg-ink text-white transition-transform lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex h-20 items-center justify-between px-6"><div><div className="text-xl font-bold">Resolve<span className="text-indigo-400">.</span></div><div className="text-[10px] uppercase tracking-[.2em] text-slate-400">Service desk</div></div><button aria-label="Close navigation" className="lg:hidden" onClick={() => setOpen(false)}><X /></button></div><nav className="space-y-1 px-3">{links.filter(link => (!link.staff || staff) && (!link.admin || admin)).map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} end={to === '/'} onClick={() => setOpen(false)} className={({ isActive }) => `flex items-center gap-3 rounded-xl px-4 py-3 text-sm ${isActive ? 'bg-indigo-500 text-white' : 'text-slate-300 hover:bg-white/5'}`}><Icon size={18} />{label}</NavLink>)}</nav><div className="absolute bottom-4 left-3 right-3"><button onClick={logout} className="flex w-full items-center gap-3 rounded-xl px-4 py-3 text-sm text-slate-300 hover:bg-white/5"><LogOut size={18} />Sign out</button></div></aside><div className="lg:pl-64"><header className="sticky top-0 z-30 flex h-20 items-center justify-between border-b border-slate-200 bg-white/90 px-4 backdrop-blur transition-colors dark:border-slate-800 dark:bg-slate-900/90 md:px-8"><div className="flex items-center gap-3"><button aria-label="Open navigation" className="lg:hidden" onClick={() => setOpen(true)}><Menu /></button><div><p className="text-sm text-slate-500 dark:text-slate-400">Welcome back,</p><h1 className="font-semibold dark:text-white">{user?.name}</h1></div></div><div className="flex items-center gap-2"><button aria-label={dark ? 'Switch to light mode' : 'Switch to dark mode'} title={dark ? 'Light mode' : 'Dark mode'} className="rounded-xl p-2.5 transition hover:bg-slate-100 dark:text-slate-200 dark:hover:bg-slate-800" onClick={() => setDark(value => !value)}>{dark ? <Sun size={19} /> : <Moon size={19} />}</button><NotificationMenu open={notificationsOpen} setOpen={setNotificationsOpen} panelRef={panelRef} /><div className="ml-2 hidden text-right sm:block"><p className="text-sm font-semibold dark:text-white">{user?.name}</p><p className="text-xs capitalize text-slate-500 dark:text-slate-400">{user?.role.replace('_', ' ')}</p></div></div></header><main className="p-4 md:p-8"><Outlet /></main></div>{open && <button aria-label="Close navigation overlay" className="fixed inset-0 z-30 bg-black/30 lg:hidden" onClick={() => setOpen(false)} />}</div>;
}

function NotificationMenu({ open, setOpen, panelRef }: { open: boolean; setOpen: (value: boolean) => void; panelRef: React.RefObject<HTMLDivElement | null> }) {
  const queryClient = useQueryClient();
  const { data = [], isLoading } = useQuery({ queryKey: ['notifications'], queryFn: () => api.get<ApiResponse<Notification[]>>('/notifications').then(response => response.data.data), refetchInterval: 30000 });
  const unread = data.filter(item => !item.readAt).length;
  const read = useMutation({ mutationFn: (id: string) => api.patch(`/notifications/${id}/read`), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['notifications'] }) });
  const markAll = async () => { await Promise.all(data.filter(item => !item.readAt).map(item => api.patch(`/notifications/${item.id}/read`))); queryClient.invalidateQueries({ queryKey: ['notifications'] }); };
  return <div className="relative" ref={panelRef}><button aria-label={`Notifications${unread ? `, ${unread} unread` : ''}`} title="Notifications" className="relative rounded-xl p-2.5 transition hover:bg-slate-100 dark:text-slate-200 dark:hover:bg-slate-800" onClick={() => setOpen(!open)}><Bell size={19} />{unread > 0 && <><span className="absolute right-1.5 top-1.5 h-2.5 w-2.5 rounded-full border-2 border-white bg-rose-500 dark:border-slate-900" />{unread > 1 && <span className="sr-only">{unread} unread</span>}</>}</button>{open && <div className="absolute right-0 top-12 w-[min(360px,calc(100vw-2rem))] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl dark:border-slate-700 dark:bg-slate-900"><div className="flex items-center justify-between border-b border-slate-100 px-4 py-3 dark:border-slate-800"><div><h3 className="font-semibold dark:text-white">Notifications</h3><p className="text-xs text-slate-500">{unread ? `${unread} unread` : 'You are all caught up'}</p></div>{unread > 0 && <button onClick={markAll} className="flex items-center gap-1 text-xs font-semibold text-brand"><CheckCheck size={15} />Mark all read</button>}</div><div className="max-h-96 overflow-y-auto">{isLoading && <div className="space-y-3 p-4">{[1,2,3].map(item => <div key={item} className="h-16 animate-pulse rounded-xl bg-slate-100 dark:bg-slate-800" />)}</div>}{!isLoading && !data.length && <div className="px-6 py-12 text-center"><Bell className="mx-auto text-slate-300" /><p className="mt-3 text-sm font-medium dark:text-slate-200">No notifications yet</p><p className="mt-1 text-xs text-slate-500">Assignments and ticket updates will appear here.</p></div>}{data.map(item => <Link key={item.id} to={item.link || '/tickets'} onClick={() => { if (!item.readAt) read.mutate(item.id); setOpen(false); }} className={`block border-b border-slate-100 px-4 py-3 transition hover:bg-slate-50 dark:border-slate-800 dark:hover:bg-slate-800 ${!item.readAt ? 'bg-indigo-50/70 dark:bg-indigo-950/30' : ''}`}><div className="flex gap-3"><span className={`mt-1.5 h-2 w-2 shrink-0 rounded-full ${item.readAt ? 'bg-slate-300 dark:bg-slate-600' : 'bg-brand'}`} /><div className="min-w-0"><p className="truncate text-sm font-semibold dark:text-slate-100">{item.title}</p><p className="mt-0.5 line-clamp-2 text-xs leading-5 text-slate-500 dark:text-slate-400">{item.message}</p><p className="mt-1 text-[10px] text-slate-400">{new Date(item.createdAt).toLocaleString()}</p></div></div></Link>)}</div></div>}</div>;
}